### ISSUE TITLE
As a Developer I would like to be able to push a new release to production with just a commit so that I can deploy new release quickly.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#399]
We want to leverage Openshift build from source to make the release of Fedora Badges much faster.

Depends on #400 

#### Tasks Breakdown
- [ ] Move dependencies to a requirements.txt file
- [ ] Add licence check to the CI run
- [ ] Configure the required s2i environment variable
- [ ] Create new playbook in infra ansible openshift-apps
- [ ] Get secrets from infra to configure github triggers

#### Acceptance Criteria
- [ ] New commit push to the staging branch, triggers an Openshift build in the staging instance
- [ ] New commit push to the production branch, triggers an Openshift build in the production instance
