### ISSUE TITLE
As a Developer I would like to have only one repository for the badges application, so that it is easier to contribute to the application.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#400]
Currently the Fedora Badges stack is composed of 3 repositories : 
 - [tahrir](https://github.com/fedora-infra/tahrir)
 - [tahrir-api](https://github.com/fedora-infra/tahrir-api)
 - [fedbadges](https://github.com/fedora-infra/fedbadges)

Ideally we want to keep the git history for each of the repository.

I am not 100% we want to merge fedbadges into the tahrir repository, to be discussed .

#### Tasks Breakdown
- [ ] Move tahrir-api into the tahrir repository 

#### Acceptance Criteria
- [ ] only one repository is needed to contribute to the fedora badges application
- [ ] A development environment is available in the repository

**Comment by mscherer** [comment]
Since we are moving to badgr, who is in 2 applications (1 API, 1 frontend), so I am closing this one. I do agree with the rational tho.
