### ISSUE TITLE
As a developer, I want to be able to see my changes directly (run the app locally with ease) before submitting them for review. I also want to be able to run a set of integration tests, so I'm sure I'm not breaking anything.

### ISSUE THREAD

**Issue by cverna** [fedora-infra/tahrir#402]
I am leaving the option open here, but if we run the application in openshift maybe a containerize development environment would make more sense.

This story depends on #400 

#### Tasks Breakdown
- [x] Update development environment so that the all Badges stack can be run locally (Webapp + Consumer
- [x] Update documentation to describe how to create the development environment
- [x] Choose and maintain only one development environment setup (Vagrant, Container, venv)
- [x] Update documentation on how to run locally the tests.

#### Acceptance Criteria
- [ ] Following the documentation I can setup my development environment.
- [ ] Using the development environment I can run the tests
